# Generated by Django 4.2.4 on 2023-09-06 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="round_two_finalists",
            field=models.ManyToManyField(
                blank=True,
                related_name="round_two_finalists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
