# Generated by Django 5.0.7 on 2024-07-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_released'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='contest',
            name='owner',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='contest.package'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='released',
            field=models.BooleanField(default=False, help_text='Release the reward to the winner'),
        ),
    ]
