# Generated by Django 4.2.4 on 2023-08-31 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("reply_to", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
