# Generated by Django 4.1.7 on 2023-03-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfeature",
            name="name",
        ),
        migrations.AddField(
            model_name="projectfeature",
            name="feature",
            field=models.CharField(default="test", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfeature",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
