# Generated by Django 4.1.7 on 2023-03-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_projectfeature_name_projectfeature_feature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfeature",
            name="feature",
            field=models.CharField(max_length=255),
        ),
    ]
