# Generated by Django 4.1.7 on 2023-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_projectfeature_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPENED", "Opened"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="OPENED",
                max_length=9,
            ),
        ),
    ]
