# Generated by Django 4.1.7 on 2023-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_alter_projectcomment_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcomment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="projectcomment",
            old_name="reply",
            new_name="parent",
        ),
    ]
