# Generated by Django 4.1.7 on 2023-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0012_alter_projectcomment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcomment",
            name="x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
