# Generated by Django 4.1.7 on 2023-04-09 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0014_project_classic_to_modern_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectdeliverable",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="projectdeliverable",
            name="designer",
        ),
        migrations.RemoveField(
            model_name="projectdeliverable",
            name="image",
        ),
        migrations.RemoveField(
            model_name="projectdeliverable",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdeliverableattachment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectdeliverableattachment",
            name="modified_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deadline", models.DateField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
