# Generated by Django 4.2 on 2023-04-16 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0015_remove_projectdeliverable_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="deadline",
        ),
    ]
