# Generated by Django 4.2 on 2023-04-16 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_remove_project_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["promote_to_top", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget_from",
        ),
        migrations.RemoveField(
            model_name="project",
            name="budget_to",
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="nda",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="promote_to_top",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
    ]
