# Generated by Django 4.2 on 2023-04-16 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0017_alter_project_options_remove_project_budget_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-promote_to_top", "-created_at"]},
        ),
    ]
