# Generated by Django 4.2 on 2023-04-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0019_rename_nda_project_nda"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
