# Generated by Django 4.2 on 2023-05-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0021_projectproposal_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdeliverableattachment",
            name="deliverable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="project.projectdeliverable",
            ),
        ),
    ]
