# Generated by Django 4.2 on 2023-08-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_projectinvitation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="languages",
            field=models.CharField(max_length=150),
        ),
    ]
