# Generated by Django 4.1.5 on 2023-01-31 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="admin",
        ),
    ]
