# Generated by Django 4.1.6 on 2023-02-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="verified",
        ),
        migrations.RemoveField(
            model_name="designerprofile",
            name="verified",
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
