# Generated by Django 4.1.6 on 2023-02-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_clientprofile_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="id_card",
            field=models.ImageField(blank=True, null=True, upload_to="id_cards/"),
        ),
        migrations.AddField(
            model_name="designerprofile",
            name="id_card",
            field=models.ImageField(blank=True, null=True, upload_to="id_cards/"),
        ),
    ]
