# Generated by Django 4.1.6 on 2023-03-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("user", "0005_userverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampledesign",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sampledesign",
            name="url",
            field=models.ImageField(upload_to="sample_designs/"),
        ),
    ]
