# Generated by Django 4.1.6 on 2023-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_sampledesign_category_alter_sampledesign_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userverification",
            name="accepted",
        ),
        migrations.AddField(
            model_name="userverification",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userverification",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
