# Generated by Django 4.1.6 on 2023-03-16 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_remove_userverification_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designerprofile",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
