# Generated by Django 4.1.7 on 2023-03-16 21:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_designerprofile_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sampledesign",
            old_name="url",
            new_name="image",
        ),
    ]
