# Generated by Django 4.1.7 on 2023-03-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_rename_url_sampledesign_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampledesign",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.designerprofile"
            ),
        ),
    ]
