# Generated by Django 4.1.7 on 2023-04-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_remove_sampledesign_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("staff", "Staff"),
                    ("client", "Client"),
                    ("designer", "Designer"),
                    ("both", "Both"),
                ],
                default=None,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="id_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userverification",
            name="id_card",
            field=models.ImageField(default=1, upload_to="id_cards/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("B", "Blocked"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
