# Generated by Django 4.1.7 on 2023-04-09 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_user_user_type_userverification_id_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
