# Generated by Django 4.2 on 2023-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_userverification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
