# Generated by Django 4.2 on 2023-04-19 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0018_notificationtopic_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationTopic",
        ),
    ]
