# Generated by Django 4.2 on 2023-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0019_delete_notification_delete_notificationtopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("facebook", "Facebook"),
                    ("email", "Email"),
                ],
                default="email",
                max_length=10,
            ),
        ),
    ]
