# Generated by Django 4.2 on 2023-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_user_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backend",
            field=models.CharField(
                default="django.contrib.auth.backends.ModelBackend", max_length=50
            ),
        ),
    ]
