# Generated by Django 5.0.7 on 2024-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_designerprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerprofile',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
