# Generated by Django 4.2 on 2023-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullprojectinvoice",
            name="payment_method",
            field=models.CharField(
                choices=[("CREDIT_CARD", "Credit Card"), ("PAYPAL", "PayPal")],
                default="PAYPAL",
                max_length=11,
            ),
            preserve_default=False,
        ),
    ]
