# Generated by Django 4.2 on 2023-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_fullprojectinvoice_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullprojectinvoice",
            name="order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="fullprojectinvoice",
            name="payer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
