# Generated by Django 4.1.6 on 2023-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_colorpalette_industry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name_plural": "Industries"},
        ),
    ]
