# Generated by Django 4.1.7 on 2023-03-25 01:00

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_category_options_alter_industry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=core.models.SVGField(upload_to="category_icons/"),
        ),
        migrations.AlterField(
            model_name="industry",
            name="icon",
            field=core.models.SVGField(upload_to="industry_icons/"),
        ),
    ]
