# Generated by Django 4.2 on 2023-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_category_icon_alter_industry_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "USD_to_EGP_rate",
                    models.DecimalField(decimal_places=5, max_digits=10),
                ),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
