# Generated by Django 4.2 on 2023-05-30 19:40

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_sitesettings_behance_url_sitesettings_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="guaranteed_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("15"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="guaranteed_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nda_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("20"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nda_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="promoted_project_duration",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="promoted_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("35"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="promoted_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
