# Generated by Django 4.2.4 on 2023-08-11 18:35

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_sitesettings_guaranteed_project_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design", models.CharField(max_length=255)),
                ("comment", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="guaranteed_project_fee",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="guaranteed_project_fee_currency",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="nda_project_fee",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="nda_project_fee_currency",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="promoted_project_duration",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="promoted_project_fee",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="promoted_project_fee_currency",
        ),
        migrations.AddField(
            model_name="category",
            name="guaranteed_contest_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("15"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="guaranteed_contest_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="guaranteed_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("15"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="guaranteed_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="nda_contest_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("20"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="nda_contest_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="nda_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("20"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="nda_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_contest_duration",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_contest_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("35"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_contest_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_project_duration",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_project_fee",
            field=djmoney.models.fields.MoneyField(
                decimal_places=5,
                default=Decimal("35"),
                default_currency="USD",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="promoted_project_fee_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EGP", "EGP €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="egyptians_discount",
            field=models.FloatField(default=0.0),
        ),
    ]
