# Generated by Django 4.2.4 on 2023-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_dispute_remove_sitesettings_guaranteed_project_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="dispute_type",
            field=models.CharField(
                choices=[("PROJECT", "Project"), ("CONTEST", "Contest")],
                default="PROJECT",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="reason",
            field=models.CharField(
                choices=[
                    ("COPIED_DESIGN", "Copied Design"),
                    ("STOCK_IMAGE", "Stock Image"),
                    ("INAPPROPRIATE_CONTENT", "Inappropriate Content"),
                ],
                default="COPIED_DESIGN",
                max_length=23,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=8,
            ),
        ),
    ]
