# Generated by Django 4.2.4 on 2023-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_dispute_dispute_type_dispute_reason_dispute_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="clarification",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WITHDRAWN", "WITHDRAWN"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=9,
            ),
        ),
    ]
