# Generated by Django 4.2.4 on 2023-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_dispute_clarification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
