# Generated by Django 4.2.4 on 2023-09-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_dispute_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DesignStyleSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="design_style_samples/")),
                (
                    "design_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.designstyle",
                    ),
                ),
            ],
        ),
    ]
