# Generated by Django 5.0.7 on 2024-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_designstyle_designstylesample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
